language: java
jdk:
  - openjdk11
env:
  matrix:
    - TYPE=test
    - TYPE=headercheck
    - TYPE=integrationtest
    - TYPE=licensecheck

cache:
  directories:
    - $HOME/.m2

before_install:
  - cd licensescout-parent

script:
  - if [[ $TYPE == test ]]; then
      mvn -Pci-modules clean install;
    elif [[ $TYPE == headercheck ]]; then
      mvn -Plicense-header-modules license:check;
    elif [[ $TYPE == integrationtest ]]; then
      mvn -Pci-for-it-modules clean install;
      mvn -DskipTests=true -Prun-its,it-modules verify;
    elif [[ $TYPE == licensecheck ]]; then
      mvn -DskipTests=true -Pci-for-it-modules clean install;
      mvn -f ../org.aposin.licensescout.licensereport verify;
    else
      echo "$TYPE type not recognized";
      exit 1;
    fi

after_success:
  - if [[ $TYPE == test ]]; then bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy; fi