language: java
jdk:
  - openjdk11
env:
  matrix:
    - TYPE=test
    - TYPE=check

cache:
  directories:
    - $HOME/.m2

before_install:
  - cd org.aposin.licensescout.parent

script:
  - if [[ $TYPE == test ]]; then
      mvn -Pci-modules clean install;
    elif [[ $TYPE == check ]]; then
      mvn -Plicense-header-modules license:check;
    else
      echo "$TYPE type not recognized";
      exit 1;
    fi

after_success:
  - if [[ $TYPE == test ]]; then bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy; fi